#pragma once
#include <cmath>
#include <functional>
#include <iomanip>
#include <iostream>
#include <map>
#include <math.h>
#include <memory>
#include <optional>
#include <sstream>
#include <string>
#include <vector>
#define _USE_MATH_DEFINES